
// src/scripts/home-client.js
import { renderModelCard } from './render-model-card.js';

// Function to fetch and render hot models (Constitution: FNI-sorted)
export async function loadHotModels() {
    const loadingEl = document.getElementById('hot-models-loading');
    const gridEl = document.getElementById('hot-models-grid');
    const errorEl = document.getElementById('hot-models-error');
    const errorMsgEl = document.getElementById('hot-models-error-msg');

    try {
        // Constitution V4.3.2: Use trending API for FNI-sorted results
        // V5.1.2: Use static R2 cache (generated by L8 Worker)
        const response = await fetch('/cache/index/trending.json');
        if (!response.ok) throw new Error(`Status: ${response.status}`);

        const data = await response.json();
        const models = (data || []).slice(0, 12);

        if (models.length === 0) {
            loadingEl.innerHTML = '<p class="col-span-full text-center text-gray-500">No hot models found.</p>';
            return;
        }

        // Render with UMID-compatible slugs
        const html = models.map(model => renderModelCard(model)).join('');

        gridEl.innerHTML = html;
        loadingEl.classList.add('hidden');
        gridEl.classList.remove('hidden');

    } catch (e) {
        console.error("Failed to load hot models:", e);
        loadingEl.classList.add('hidden');
        errorEl.classList.remove('hidden');
        errorMsgEl.textContent = e.message || "Failed to fetch data";
    }
}

// V4.9.1: Weekly Report Banner Loader
export async function loadWeeklyReport() {
    const banner = document.getElementById('weekly-report-banner');
    const titleEl = document.getElementById('report-title');
    const summaryEl = document.getElementById('report-summary');
    const topModelEl = document.getElementById('report-top-model');
    const topModelLink = document.getElementById('report-top-model-link');

    try {
        // Get current week number
        const now = new Date();
        const startOfYear = new Date(now.getFullYear(), 0, 1);
        const weekNum = Math.ceil((((now.getTime() - startOfYear.getTime()) / 86400000) + startOfYear.getDay() + 1) / 7);
        const reportKey = `${now.getFullYear()}-W${String(weekNum).padStart(2, '0')}`;

        // Fetch latest report
        const response = await fetch(`/reports/${reportKey}.json`);
        let data;

        if (!response.ok) {
            // Try previous week if current doesn't exist
            const prevWeek = weekNum - 1;
            const prevReportKey = `${now.getFullYear()}-W${String(prevWeek).padStart(2, '0')}`;
            const prevResponse = await fetch(`/reports/${prevReportKey}.json`);
            if (!prevResponse.ok) throw new Error('No report available');
            data = await prevResponse.json();
        } else {
            data = await response.json();
        }

        // Populate banner
        titleEl.textContent = `Week ${data.week || weekNum} AI Trends`;

        if (data.this_week_changed?.fni_leader) {
            const leader = data.this_week_changed.fni_leader;
            summaryEl.textContent = `${data.this_week_changed.new_models_count || 0} new models this week!`;
            topModelEl.textContent = leader.name;
            topModelLink.href = `/model/${leader.slug}`;
        } else if (data.who_to_watch?.[0]) {
            const top = data.who_to_watch[0];
            summaryEl.textContent = data.why_it_matters?.summary?.slice(0, 100) + '...' || 'Check out this week\'s top models';
            topModelEl.textContent = top.name;
            topModelLink.href = `/model/${top.slug}`;
        }

        // Show banner
        banner.classList.remove('hidden');
    } catch (e) {
        console.log('[WeeklyReport] No report available:', e.message);
        // Banner stays hidden if no report
    }
}
