
// src/scripts/home-client.js
import { renderModelCard } from './render-model-card.js';

// Function to fetch and render hot models (Constitution: FNI-sorted)
export async function loadHotModels() {
    const loadingEl = document.getElementById('hot-models-loading');
    const gridEl = document.getElementById('hot-models-grid');
    const errorEl = document.getElementById('hot-models-error');
    const errorMsgEl = document.getElementById('hot-models-error-msg');

    try {
        // Constitution V4.3.2: Use trending API for FNI-sorted results
        // V5.1.2: Use R2 cache API proxy (generated by L8 Worker)
        const response = await fetch('/api/cache/trending.json');
        if (!response.ok) throw new Error(`Status: ${response.status}`);

        const data = await response.json();
        const models = (data.models || data || []).slice(0, 12);

        if (models.length === 0) {
            loadingEl.innerHTML = '<p class="col-span-full text-center text-gray-500">No hot models found.</p>';
            return;
        }

        // Render with UMID-compatible slugs
        const html = models.map(model => renderModelCard(model)).join('');

        gridEl.innerHTML = html;
        loadingEl.classList.add('hidden');
        gridEl.classList.remove('hidden');

    } catch (e) {
        console.error("Failed to load hot models:", e);
        loadingEl.classList.add('hidden');
        errorEl.classList.remove('hidden');
        errorMsgEl.textContent = e.message || "Failed to fetch data";
    }
}

// V4.9.1: Weekly Report Banner Loader
export async function loadWeeklyReport() {
    const banner = document.getElementById('weekly-report-banner');
    const titleEl = document.getElementById('report-title');
    const summaryEl = document.getElementById('report-summary');
    const topModelEl = document.getElementById('report-top-model');
    const topModelLink = document.getElementById('report-top-model-link');

    if (!banner) return;

    try {
        // Get current week number
        const now = new Date();
        const startOfYear = new Date(now.getFullYear(), 0, 1);
        const weekNum = Math.ceil((((now.getTime() - startOfYear.getTime()) / 86400000) + startOfYear.getDay() + 1) / 7);
        const reportKey = `${now.getFullYear()}-W${String(weekNum).padStart(2, '0')}`;

        // Fetch latest report
        const response = await fetch(`/reports/${reportKey}.json`);
        let data;

        if (!response.ok) {
            // Try previous week if current doesn't exist
            const prevWeek = weekNum - 1;
            const prevReportKey = `${now.getFullYear()}-W${String(prevWeek).padStart(2, '0')}`;
            const prevResponse = await fetch(`/reports/${prevReportKey}.json`);
            if (!prevResponse.ok) throw new Error('No report available');
            data = await prevResponse.json();
        } else {
            data = await response.json();
        }

        // Populate banner
        titleEl.textContent = `Week ${data.week || weekNum} AI Trends`;

        if (data.this_week_changed?.fni_leader) {
            const leader = data.this_week_changed.fni_leader;
            const leaderType = leader.type || 'model';
            const leaderPrefix = leaderType === 'agent' ? '/agent/' : leaderType === 'dataset' ? '/dataset/' : leaderType === 'tool' ? '/tool/' : leaderType === 'paper' ? '/paper/' : '/model/';
            summaryEl.textContent = `${data.this_week_changed.new_models_count || 0} new models this week!`;
            topModelEl.textContent = leader.name;
            topModelLink.href = `${leaderPrefix}${leader.slug.replace(/^[a-z]+:/i, '').replace(/^(model|agent|dataset|tool|paper|space)s?\//i, '')}`;
        } else if (data.who_to_watch?.[0]) {
            const top = data.who_to_watch[0];
            const topType = top.type || 'model';
            const topPrefix = topType === 'agent' ? '/agent/' : topType === 'dataset' ? '/dataset/' : topType === 'tool' ? '/tool/' : topType === 'paper' ? '/paper/' : '/model/';
            summaryEl.textContent = data.why_it_matters?.summary?.slice(0, 100) + '...' || 'Check out this week\'s top models';
            topModelEl.textContent = top.name;
            topModelLink.href = `${topPrefix}${top.slug.replace(/^[a-z]+:/i, '').replace(/^(model|agent|dataset|tool|paper|space)s?\//i, '')}`;
        }

        // Show banner
        banner.classList.remove('hidden');
    } catch (e) {
        console.log('[WeeklyReport] No report available, falling back to trending:', e.message);

        // Fallback: Use trending data instead
        try {
            const trendingRes = await fetch('/api/cache/trending.json');
            if (trendingRes.ok) {
                const trendingData = await trendingRes.json();
                const topModel = trendingData.models?.[0];

                if (topModel) {
                    const now = new Date();
                    const weekNum = Math.ceil((now.getTime() - new Date(now.getFullYear(), 0, 1).getTime()) / (7 * 24 * 60 * 60 * 1000));

                    titleEl.textContent = `Week ${weekNum} AI Trends`;
                    summaryEl.textContent = `${trendingData.count || 100} trending models this week!`;
                    topModelEl.textContent = topModel.name;

                    const topModelType = topModel.type || 'model';
                    const topModelPrefix = topModelType === 'agent' ? '/agent/' : topModelType === 'dataset' ? '/dataset/' : topModelType === 'tool' ? '/tool/' : topModelType === 'paper' ? '/paper/' : '/model/';
                    topModelLink.href = `${topModelPrefix}${topModel.slug.replace(/^[a-z]+:/i, '').replace(/^(model|agent|dataset|tool|paper|space)s?\//i, '')}`;

                    banner.classList.remove('hidden');
                }
            }
        } catch (fallbackErr) {
            console.log('[WeeklyReport] Fallback also failed, hiding banner');
            // Banner stays hidden
        }
    }
}

