
// src/scripts/home-client.js
import { renderModelCard } from './render-model-card.js';

// Function to fetch and render hot models (Constitution: FNI-sorted)
export async function loadHotModels() {
    const loadingEl = document.getElementById('hot-models-loading');
    const gridEl = document.getElementById('hot-models-grid');
    const errorEl = document.getElementById('hot-models-error');
    const errorMsgEl = document.getElementById('hot-models-error-msg');

    try {
        // Constitution V4.3.2: Use trending API for FNI-sorted results
        // V5.1.2: Use R2 cache API proxy (generated by L8 Worker)
        const response = await fetch('https://cdn.free2aitools.com/cache/trending.json');
        if (!response.ok) throw new Error(`Status: ${response.status}`);

        const data = await response.json();
        const models = (data.models || data || []).slice(0, 12);

        if (models.length === 0) {
            loadingEl.innerHTML = '<p class="col-span-full text-center text-gray-500">No hot models found.</p>';
            return;
        }

        // Render with UMID-compatible slugs
        const html = models.map(model => renderModelCard(model)).join('');

        gridEl.innerHTML = html;
        loadingEl.classList.add('hidden');
        gridEl.classList.remove('hidden');

    } catch (e) {
        console.error("Failed to load hot models:", e);
        loadingEl.classList.add('hidden');
        errorEl.classList.remove('hidden');
        errorMsgEl.textContent = e.message || "Failed to fetch data";
    }
}

// V16.8.1: Daily Report Banner Loader (Standardized to YYYY-MM-DD + 7-Day Fallback)
export async function loadDailyReport() {
    const banner = document.getElementById('daily-report-banner');
    const titleEl = document.getElementById('report-title');
    const summaryEl = document.getElementById('report-summary');
    const topModelEl = document.getElementById('report-top-model');
    const topModelLink = document.getElementById('report-top-model-link');

    if (!banner) return;

    try {
        const now = new Date();
        let reportData = null;
        let foundDate = null;

        // Try last 7 days (Daily reports are prioritized)
        for (let i = 0; i < 7; i++) {
            const date = new Date(now);
            date.setDate(now.getDate() - i);
            const dateKey = date.toISOString().split('T')[0]; // YYYY-MM-DD

            try {
                const response = await fetch(`https://cdn.free2aitools.com/cache/reports/daily/${dateKey}.json`);
                if (response.ok) {
                    reportData = await response.json();
                    foundDate = dateKey;
                    break;
                }
            } catch (e) {
                continue;
            }
        }

        if (!reportData) throw new Error('No recent daily report found');

        // Populate banner with Daily nomenclature
        titleEl.textContent = `Daily AI Update: ${foundDate}`;

        // V16.8.1: Support both legacy 'this_week_changed' and new 'daily_brief' structures
        const briefing = reportData.daily_brief || reportData.this_week_changed || {};
        const leader = briefing.fni_leader || (reportData.who_to_watch ? reportData.who_to_watch[0] : null);

        if (leader) {
            const leaderType = leader.type || 'model';
            const leaderPrefix = leaderType === 'agent' ? '/agent/' : leaderType === 'dataset' ? '/dataset/' : leaderType === 'tool' ? '/tool/' : leaderType === 'paper' ? '/paper/' : '/model/';
            const count = briefing.new_entities_count || briefing.new_models_count || 0;

            summaryEl.textContent = count > 0 ? `${count} new entities tracked today!` : 'Review the latest FNI leaderboards.';
            topModelEl.textContent = leader.name;
            topModelLink.href = `${leaderPrefix}${leader.slug.replace(/^[a-z]+:/i, '').replace(/^(model|agent|dataset|tool|paper|space)s?\//i, '')}`;
        }

        banner.classList.remove('hidden');
    } catch (e) {
        console.warn('[DailyReport] Daily fetch failed, falling back to legacy/trending:', e.message);

        // Final fallback: Use trending.json
        try {
            const trendingRes = await fetch('https://cdn.free2aitools.com/cache/trending.json');
            if (trendingRes.ok) {
                const trendingData = await trendingRes.json();
                const topModel = trendingData.models?.[0];

                if (topModel) {
                    titleEl.textContent = `Daily AI Pulse`;
                    summaryEl.textContent = `${trendingData.count || 100} top-rated entities today.`;
                    topModelEl.textContent = topModel.name;

                    const topModelType = topModel.type || 'model';
                    const topModelPrefix = topModelType === 'agent' ? '/agent/' : topModelType === 'dataset' ? '/dataset/' : topModelType === 'tool' ? '/tool/' : topModelType === 'paper' ? '/paper/' : '/model/';
                    topModelLink.href = `${topModelPrefix}${topModel.slug.replace(/^[a-z]+:/i, '').replace(/^(model|agent|dataset|tool|paper|space)s?\//i, '')}`;

                    banner.classList.remove('hidden');
                }
            }
        } catch (fallbackErr) {
            console.error('[DailyReport] All fallbacks failed.');
        }
    }
}

