/**
 * N-P5 item 0b (G-3), case B in counterexamples.sh -- what can be checked OFF a
 * runner: SOURCE-TEXT pins only. Nothing here executes the launcher, the stub
 * or any mutant, so nothing here shows the pre-phase-d P-1 gate failing. That
 * evidence exists only in the CI run that executes the driver: rc 76 from
 * exit-codes.sh, phaseC.rc 0, no phaseD.* on case B itself; phase D STARTED on
 * each of the M-B1..M-B5 copies.
 *
 * LIMIT: the pins guard the TEXT of the case B region (helpers/caseb-pins.mjs)
 * and, through P4 of helpers/p9o-pins.mjs, the whole-driver declaration census.
 * Edits OUTSIDE the region that add no declaration can still neutralise the
 * case without tripping them (the same limit the P9o pins state).
 */
import { describe, it, expect } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const ISO = path.join(ROOT, 'scripts', 'ci', 'isolation');
const DRIVER = path.join(ISO, 'counterexamples.sh');
const FIXTURE = path.join(ROOT, 'tests', 'ci', 'fixtures', 'wo-n-p5-0b', 'caseb-code-region.txt');
const HELPER = path.join(ROOT, 'tests', 'ci', 'helpers', 'caseb-pins.mjs');
const lf = (p: string): string => fs.readFileSync(p, 'utf8').replace(/\r\n/g, '\n');
const codeLines = (p: string): string[] => lf(p).split('\n').filter((l) => !/^\s*(\/\/|\/\*|\*)/.test(l));

describe('case B: source-text pins (none of this is runtime behaviour)', () => {
    it('the case B region, its load-bearing lines and the kill-check order hold', async () => {
        const { casebPinFailures } = await import('./helpers/caseb-pins.mjs');
        expect(casebPinFailures(lf(DRIVER), lf(FIXTURE))).toEqual([]);
    });

    it('the pins are not vacuous: dropping any one region line from the driver is caught', async () => {
        const { casebPinFailures } = await import('./helpers/caseb-pins.mjs');
        const driver = lf(DRIVER).split('\n');
        const region = lf(FIXTURE).replace(/\n$/, '').split('\n');
        const start = driver.indexOf(region[0]);
        expect(start).toBeGreaterThan(0);
        for (let i = start; i < driver.length && driver[i] !== region[region.length - 1]; i += 1) {
            if (/^\s*#/.test(driver[i])) continue;
            const cut = [...driver.slice(0, i), ...driver.slice(i + 1)].join('\n');
            expect(casebPinFailures(cut, lf(FIXTURE)).length, `line ${i + 1}`).toBeGreaterThan(0);
        }
    });

    it('the fixture itself: sha256 of its LF-normalised content', () => {
        // The literal was written from a command's output over the fixture, which
        // was itself generated by command from the driver's code lines.
        expect(createHash('sha256').update(lf(FIXTURE)).digest('hex'))
            .toBe('49a9034961a750a02ab4acffb0fcc8fd4132e4c37ef321dd815e5bc85b467ed5');
    });

    it('the helper is pure: no env, fs, import or require token on a code line, one export', () => {
        const tok = ['process', 'env'].join('.');
        const helper = codeLines(HELPER);
        expect(helper.filter((l) => l.includes(tok)
            || /readFileSync|\bfs\.|\bimport\b|\brequire\s*\(/.test(l))).toEqual([]);
        expect(helper.filter((l) => /^\s*export\b/.test(l)))
            .toEqual(['export function casebPinFailures(driverText, fixtureText) {']);
    });

    it('each mutant anchor starts exactly one line of the frozen file it edits, and the '
        + 'stub-curl.sh sentinel anchor is exactly one whole line', () => {
        const starts = (f: string, a: string): number => lf(path.join(ISO, f)).split('\n')
            .filter((l) => l.startsWith(a)).length;
        for (const a of ['f2ai_stub_verify "$STUB_MANIFEST" "$EVID" "pre-phase-d"',
            'rec "stub identity (pre-phase-d) rc=$STUB_RC"', '# ------------------------- cache now exists']) {
            expect(starts('netns-phases.sh', a), a).toBe(1);
        }
        expect(starts('stub-identity.sh', '  : >"$report"')).toBe(1);
        expect(lf(path.join(ISO, 'stub-curl.sh')).split('\n')
            .filter((l) => l === 'if [ "${1-}" = "--f2ai-iso-sentinel" ]; then').length).toBe(1);
    });
});
