/**
 * Work order N -- executable contract for ruling B (the strict option)
 * and for the parts of ruling C that are settled statically.
 *
 * §B  the classified channel list is EXPLICIT and read from a file (b2); the
 *     masking is load-bearing and a failure aborts at establish with 71 (b1);
 *     the comments say so rather than contradicting the code (b3); and nothing
 *     in the audit path connects to a live socket any more.
 * §C  exit-codes.sh no longer claims a reserved range (c1); the timeout source
 *     is recorded positively at both layers (c3); the single attribution
 *     artifact is generated by the launcher (c5).
 */
import { describe, it, expect } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const DIR = path.join(ROOT, 'scripts', 'ci', 'isolation');
const read = (f: string): string => fs.readFileSync(path.join(DIR, f), 'utf8').replace(/\r\n/g, '\n');
const LIST = 'classified-channels.tsv';

type Row = { cls: string; match: string; target: string; mask: string; why: string };
const rows = (): Row[] => read(LIST).split('\n')
    .filter((l) => l.trim() && !l.startsWith('#'))
    .map((l) => {
        const [cls, match, target, mask, why] = l.split('\t');
        return { cls, match, target, mask, why };
    });

describe('b2: the classified channel list is explicit and machine-read', () => {
    it('the list parses, and every row is well formed', () => {
        const all = rows();
        expect(all.length).toBeGreaterThanOrEqual(10);
        for (const r of all) {
            expect(['CLASSIFIED', 'RECORD_ONLY'], `bad class in ${r.target}`).toContain(r.cls);
            expect(['PATH', 'PATTERN'], `bad match in ${r.target}`).toContain(r.match);
            expect(['TMPFS_DIR', 'BIND_NULL', 'NONE'], `bad mask in ${r.target}`).toContain(r.mask);
            expect(r.why && r.why.length, `no rationale for ${r.target}`).toBeTruthy();
        }
    });

    it('it names the channels the ruling calls out, each classified', () => {
        const classified = rows().filter((r) => r.cls === 'CLASSIFIED');
        const joined = classified.map((r) => r.target).join(' ');
        for (const needle of ['docker', 'containerd', 'dbus', 'systemd/resolve', 'gpg-agent']) {
            expect(joined, `${needle} must be classified`).toContain(needle);
        }
        expect(classified.filter((r) => r.match === 'PATH').length).toBeGreaterThanOrEqual(8);
        expect(classified.filter((r) => r.match === 'PATTERN').length).toBeGreaterThanOrEqual(4);
    });

    it('every PATTERN row compiles as a regular expression', () => {
        for (const r of rows().filter((x) => x.match === 'PATTERN')) {
            expect(() => new RegExp(r.target), `bad pattern ${r.target}`).not.toThrow();
        }
    });

    it('no channel path or pattern is hardcoded in the scripts any more', () => {
        // The whole point of b2: "classified" has to be checkable in one place.
        const consumers = ['mask-channels.sh', 'netns-ipc.mjs', 'netns-establish.sh',
            'netns-selftest.mjs', 'netns-launch.sh', 'netns-phases.sh',
            'finalize.sh', 'attribute.mjs', 'attribution-cases.sh',
            'boundary-precondition.mjs', 'counterexamples.sh', 'case-helpers.sh'];
        for (const f of consumers) {
            const src = read(f);
            for (const needle of ['/run/dbus', '/run/docker', 'docker.sock',
                'containerd.sock', 'io.systemd.Resolve', 'SSH_AUTH_SOCK']) {
                expect(src, `${f} must not hardcode ${needle}`).not.toContain(needle);
            }
        }
    });

    it('both consumers read the list from the file', () => {
        expect(read('mask-channels.sh')).toContain('$tsv');
        expect(read('netns-establish.sh')).toContain('classified-channels.tsv');
        expect(read('netns-ipc.mjs')).toContain("'classified-channels.tsv'");
    });
});

describe('b1/b3: the masking is load-bearing and the comments say so', () => {
    it('a classified masking failure aborts at establish with 71', () => {
        const src = read('netns-establish.sh');
        expect(src).toContain('f2ai_mask_classified');
        expect(src).toMatch(/MASK_RC" -ne 0/);
        expect(src).toContain('F2AI_ISO_RC_ESTABLISH');
        // The abort must come BEFORE the privilege drop and therefore before
        // phase C could ever run.
        expect(src.indexOf('MASK_RC')).toBeLessThan(src.indexOf('exec "${ENVV[@]}"'));
    });

    it('the establish comment no longer calls phase C the load-bearing part', () => {
        const src = read('netns-establish.sh');
        expect(src).not.toContain('the load-bearing part is the phase C VERIFICATION');
        expect(src).not.toMatch(/N3-3 host IPC mitigation \(BEST EFFORT/);
        expect(src).toContain('THE MASKING ITSELF IS LOAD-BEARING');
        expect(src).toContain('Nothing here is filed under limitation L5');
    });

    it('the launcher header describes the same model as the code', () => {
        const src = read('netns-launch.sh');
        expect(src).not.toContain('a reachable network-capable channel FAILS the self-test');
        expect(src).toContain('The masking is the defence');
    });

    it('the audit path performs no connect on any channel', () => {
        const src = read('netns-ipc.mjs');
        expect(src).not.toContain('net.connect');
        expect(src).not.toContain("import net from 'node:net'");
        expect(src).toContain('stat(2) only');
        expect(read('netns-selftest.mjs')).not.toContain('auditChannels');
    });

    it('the b4 fault knob can only add a failure', () => {
        const src = read('mask-channels.sh');
        expect(src).toContain('FORCED_FAILURE');
        expect(src).toContain('failures=$((failures + 1))');
        // It must not be able to SKIP a masking and continue.
        expect(src).not.toMatch(/fault.*=.*skip/i);
    });
});

describe('c1: the exit-code comment is corrected', () => {
    const src = read('exit-codes.sh');

    it('the reserved-range claim is retracted, not merely reworded', () => {
        // The correction QUOTES the old wording so the record shows what was
        // withdrawn. What must not survive is the claim standing unrefuted, so
        // the retraction has to follow the quote.
        expect(src).toContain('THAT WAS FALSE');
        const quoted = src.indexOf('can only be produced by the launcher');
        if (quoted >= 0) {
            expect(src.indexOf('THAT WAS FALSE')).toBeGreaterThan(quoted);
            expect(src).toContain('An earlier version of this comment claimed');
        }
        expect(src).toContain('is free to exit 70, 71, 74 or 124');
    });

    it('it states that codes are not remapped and are not the criterion', () => {
        expect(src).toContain('INTENTIONAL HONESTY PROPERTY');
        expect(src).toContain('NOT THE PRIMARY CRITERION FOR ATTRIBUTION');
        expect(src).toContain('The codes are NOT remapped');
        expect(src).toContain('never remapped');
    });
});

describe('c3/c5: the timeout source and the single artifact', () => {
    it('phase D records a source for EVERY 124, so nothing is read from an absence', () => {
        // The write must be guarded only by the exit code; the measurement
        // chooses the VALUE. If the elapsed-time test gated the write instead,
        // "the program returned 124 itself" would be the absence of a record --
        // exactly what c3 forbids.
        const src = read('netns-phases.sh');
        expect(src).toMatch(/if \[ "\$D_RC" -eq 124 \]; then/);
        expect(src).toContain('D_TS=inner');
        expect(src).toContain('D_TS=program');
        expect(src).toContain("printf 'phaseD.timeout-source=%s\\n");
        expect(src).toMatch(/D_ELAPSED" -ge "\$PHASE_D_DEADLINE"/);
        expect(src).toContain('phaseD.timing');
        // The guard for the write is the code alone: no `-f` existence test and
        // no elapsed-time test on the same `if` line as the 124 comparison.
        const guard = src.split('\n').find((l) => l.includes('"$D_RC" -eq 124')) ?? '';
        expect(guard).not.toContain('D_ELAPSED');
        expect(guard).not.toContain('-f ');
    });

    it('the outer source is written FIRST on signal arrival', () => {
        const src = read('netns-launch.sh');
        const write = src.indexOf('launcher.timeout-source=outer');
        const kill = src.indexOf('kill -TERM "$CHILD"');
        expect(write).toBeGreaterThan(0);
        expect(write, 'the record must be written before any cleanup').toBeLessThan(kill);
        expect(src).toContain('trap on_signal INT TERM');
    });

    it('the outer layer records a value for a 124 it did NOT cause', () => {
        const src = read('netns-launch.sh');
        expect(src).toContain('L_TS=outer');
        expect(src).toContain('L_TS=propagated');
        // Same shape as the inner layer: the code alone opens the record, the
        // measurement picks which value goes in it.
        const guard = src.split('\n').find((l) => l.includes('"$CHILD_RC" -eq 124')) ?? '';
        expect(guard).not.toContain('L_ELAPSED');
    });

    it('attribution branches on the recorded VALUE, never on file existence', () => {
        const src = read('attribute.mjs');
        expect(src).toContain("R.launcherTimeoutSource === 'outer'");
        expect(src).toContain("R.phaseDTimeoutSource === 'inner'");
        // A 124 with no source recorded is named, not resolved by guesswork.
        expect(src).toContain('PROGRAM_INDETERMINATE');
        expect(src).toContain('no timeout source was recorded');
        expect(src).toContain('record.phaseD_timeout_source');
        expect(src).toContain('record.launcher_timeout_source');
    });

    it('the launcher generates exactly one attribution artifact, on every path', () => {
        const src = read('netns-launch.sh');
        // The artifact's name and its generator live in finalize.sh, which the
        // launcher sources; there is exactly one producer of the file.
        const fin = read('finalize.sh');
        expect(fin).toContain('attribution.txt');
        expect(fin).toContain('attribute.mjs');
        expect(src).toContain('. "$HERE/finalize.sh"');
        expect(src).not.toContain('attribute.mjs');
        // Generating it must not be able to change the outcome.
        expect(src).toMatch(/exit "\$CHILD_RC"/);
        expect(src).toContain('f2ai_finalize "$CHILD_RC"');
        expect(src).toContain('f2ai_finalize "$2"');
        expect((src.match(/f2ai_finalize/g) ?? []).length).toBeGreaterThanOrEqual(3);
    });

    it('the c4 discriminating cases are registered and reachable', () => {
        expect(read('counterexamples.sh')).toContain('attribution-cases.sh');
        const cases = read('attribution-cases.sh');
        for (const c of ['c4-exit70', 'c4-exit71', 'c4-exit124', 'c3-inner-timeout', 'c4-pass']) {
            expect(cases, `case ${c} missing`).toContain(c);
        }
        expect(cases).toContain('exit "$FAILED"');
        // The handover must ADD the sub-driver's failures, never swallow them.
        expect(read('counterexamples.sh')).toContain('FAILED=$((FAILED + ATTR_CASES_RC))');
    });
});
