export async function onRequest(context) {
    const url = new URL(context.request.url);
    // Serve the pre‑built placeholder page for any /model/* request.
    // The placeholder page is generated by the Astro route with slug "_placeholder".
    const staticPage = new URL('/model/_placeholder', url.origin);
    return context.env.ASSETS.fetch(staticPage);
}
