/**
 * Sitemap Index Proxy
 * V6.1: Serves sitemap-index.xml from R2
 * 
 * The actual sitemap is generated by L5 (l5_sitemap_gen.py) and stored in R2.
 * This route proxies the request to R2 via Custom Domain for edge serving.
 */

import type { APIRoute } from 'astro';

const R2_CDN_BASE = 'https://cdn.free2aitools.com';

export const GET: APIRoute = async () => {
    try {
        // Try to fetch from R2 CDN
        const r2Url = `${R2_CDN_BASE}/sitemaps/sitemap-index.xml`;
        const response = await fetch(r2Url);

        if (response.ok) {
            const content = await response.text();
            return new Response(content, {
                status: 200,
                headers: {
                    'Content-Type': 'application/xml',
                    'Cache-Control': 'public, max-age=3600',
                },
            });
        }

        // Fallback: Generate minimal sitemap index
        const now = new Date().toISOString().split('T')[0];
        const fallbackXml = `<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <sitemap>
    <loc>https://free2aitools.com/sitemap-static.xml</loc>
    <lastmod>${now}</lastmod>
  </sitemap>
</sitemapindex>`;

        return new Response(fallbackXml, {
            status: 200,
            headers: {
                'Content-Type': 'application/xml',
                'Cache-Control': 'public, max-age=3600',
            },
        });
    } catch (error) {
        // Emergency fallback
        return new Response('<?xml version="1.0"?><sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"></sitemapindex>', {
            status: 200,
            headers: { 'Content-Type': 'application/xml' },
        });
    }
};
