/**
 * AI Summary Reader - L8 Utility
 * 
 * Loads AI-generated summaries from R2 cache for use in hydration.
 * Structure: Map<modelId, summary> for O(1) lookup (Helios approved)
 * 
 * Constitution Compliance:
 * - Art 1.2: L8 only reads cached data, no AI inference
 * - Art 2.2: Summaries generated by L5 with zero fabrication prompt
 */

import { Env } from '../config/types';

// Cache AI summaries in memory for the duration of the worker invocation
let cachedSummaries: Map<string, string> | null = null;
let cacheLoadedAt: number = 0;
const CACHE_TTL_MS = 5 * 60 * 1000; // 5 minutes

interface AiSummaryData {
    version: string;
    generated_at: string;
    model: string;
    fni_threshold: number;
    total_count: number;
    summaries: Record<string, string>;
}

/**
 * Load AI summaries from R2 cache
 * Returns Map for O(1) lookup performance
 */
export async function loadAiSummaries(env: Env): Promise<Map<string, string>> {
    // Check if cached and still valid
    const now = Date.now();
    if (cachedSummaries && (now - cacheLoadedAt) < CACHE_TTL_MS) {
        return cachedSummaries;
    }

    try {
        const object = await env.R2_ASSETS.get('cache/ai-summaries.json.gz');

        if (!object) {
            console.log('[AiSummary] No ai-summaries.json found in R2');
            cachedSummaries = new Map();
            cacheLoadedAt = now;
            return cachedSummaries;
        }

        // Decompress and parse
        const compressedData = await object.arrayBuffer();
        const decompressedStream = new Response(compressedData).body!
            .pipeThrough(new DecompressionStream('gzip'));
        const text = await new Response(decompressedStream).text();

        const data: AiSummaryData = JSON.parse(text);

        // Convert to Map for O(1) lookup
        cachedSummaries = new Map(Object.entries(data.summaries));
        cacheLoadedAt = now;

        console.log(`[AiSummary] Loaded ${cachedSummaries.size} AI summaries (generated: ${data.generated_at})`);

        return cachedSummaries;

    } catch (error) {
        console.error('[AiSummary] Failed to load:', error);
        cachedSummaries = new Map();
        cacheLoadedAt = now;
        return cachedSummaries;
    }
}

/**
 * Get AI summary for a specific model
 * Returns null if no AI summary exists (fallback to template)
 */
export async function getAiSummary(env: Env, modelId: string): Promise<string | null> {
    const summaries = await loadAiSummaries(env);
    return summaries.get(modelId) || null;
}

/**
 * Check if model has AI summary
 */
export async function hasAiSummary(env: Env, modelId: string): Promise<boolean> {
    const summaries = await loadAiSummaries(env);
    return summaries.has(modelId);
}
